baseURL = 'https://gemeinsam-warm.de/'
languageCode = 'de-de'
title = 'Nahwärme für Jossgrund'
theme = 'basic'

# sectionPagesMenu = 'main'

[menu]
  # [[menu.main]]
    # identifier = "main"
    # name = "Startseite"
    # url = "/"
    # weight = 1
  [[menu.main]]
    identifier = "grundlagen"
    name = "Grundlagen"
    url = "/grundlagen"
    weight = 2
  [[menu.main]]
    identifier = "grundlagen_allgemein"
    name = "Allgemein"
    url = "/grundlagen"
    parent = "grundlagen"
    weight = 1
  [[menu.main]]
    identifier = "zeitplan"
    name = "Zeitplan"
    url = "/grundlagen/zeitplan"
    parent = "grundlagen"
    weight = 2
  [[menu.main]]
    identifier = "finanzierung"
    name = "Finanzierung"
    url = "/grundlagen/finanzierung"
    parent = "grundlagen"
    weight = 3
  [[menu.main]]
    identifier = "technik"
    name = "Technik"
    url = "/technik"
    weight = 3
  [[menu.main]]
    identifier = "alskunde"
    name = "Als Kunde"
    url = "/technik/alskunde"
    parent = "technik"
    weight = 1
  [[menu.main]]
    identifier = "netz"
    name = "Netz"
    url = "/technik/netz"
    parent = "technik"
    weight = 2
  [[menu.main]]
    identifier = "waermeerzeugung"
    name = "Wärmeerzeugung"
    url = "/technik/waermeerzeugung"
    parent = "technik"
    weight = 3
